### PR TITLE
Features/video4linux jpeg

### PR DESCRIPTION
**Pull request by scotty007**
Adds JPEG pixel format support for video4linux cameras.

### CODE REVIEW

**Comment by uzadow** [comment]
Very nice! What cameras does this work with?

Two comments:
- libjpeg will always be installed if libavg is installed, because it's a dependency of gdk-pixbuf (also, otherwise we wouldn't be able to load jpegs :-)). We don't need #ifdefs there, and the configure check can throw an error if libjpeg isn't there. You could also see if we need the configure check at all - I'm not sure. After all, the library should always be linked already.
- There are a few lines with only whitespace changes in PixelFormat.h. That messes up the history/git blame output and makes it harder to find the commits that caused bugs.

Do you have the time to fix these?

**Comment by scotty007** [comment]
Right now I have access only to a JPEG camera that's not freely available. It is part of a headset (available here: https://pupil-labs.com/). Would be great to test more than this one...

The comments:
* No, there's no libjpeg-dev package installed on a clean Ubuntu installation after fetching all libavg dependencies, only the binary package (just checked 14.04). If this would go to the master branch, I wanted to add a note on the installation guide [page](https://www.libavg.de/site/projects/libavg/wiki/UbuntuSourceInstall) (similar to libxi-dev).
* Hmm, if I just add back the removed whitespaces in a new commit, it will still be in the history. Is there another way than creating a new branch with a "clean" commit?

**Comment by uzadow** [comment]
- I would just add libjpeg-dev to the list of libavg dependencies, no need to make it optional. #ifdef stuff tends to break, because we never check all paths while building.
- Yeah, you would probably want to undo the commit and redo it without whitespace changes. You're the only one working on the branch? Then you do a `git push -f` (second answer here: http://stackoverflow.com/questions/22682870/git-undo-pushed-commits). Or just create a new branch...

**Comment by scotty007** [comment]
Ok, I'll create a new branch w/o #ifdefs and whitespace changes...

**Pull request closed without merging**
