### PR TITLE
Updated Player to work with newer libavcodec

### PR DESCRIPTION
**Pull request by hellbender3069**

### CODE REVIEW

**Comment by uzadow** [comment]
Should I pull this now or are more changes of this sort comming?

Also, can you update to current master and see what happens? I had to roll back one line of the last pull request because it broke for certain libav versions (see http://www.libavg.de/bb/builders/i386-win-incr/builds/3130/steps/shell/logs/stdio).

**Comment by hellbender3069** [comment]
Wait I will check the buildlog and see what is wrong with that line of code. It should mot break the build

Date: Thu, 7 Jan 2016 09:20:20 -0800

**Comment by uzadow** [comment]
Um - I already undid that one line in master so the build is stable: 338828130432b6116b7f743c3cd80d3e0c9ee6e9

**Comment by uzadow** [comment]
Should be fixed with current git.

**Pull request closed without merging**
