### PR TITLE
Possible fix to #636, it does not address the root cause on DisplayEngine

### PR DESCRIPTION
**Pull request by oxullo**
@uzadow, please check the implications and if there's a greater scope to take into consideration. It solves the issue to me

### CODE REVIEW

**Comment by uzadow** [comment]
I believe the calculation scales touch coordinates if app-resolution != app-window-size.
Could you check if your patch breaks with
$ avg_checktouch.py --app-window-size=1024x768
?

If so, we'll need to fix the bug at the source.

**Comment by uzadow** [comment]
Can't test here, but can you check if this fixes it?

    diff --git a/src/player/DisplayEngine.cpp b/src/player/DisplayEngine.cpp
    index 8e87225..626255d 100644
    --- a/src/player/DisplayEngine.cpp
    +++ b/src/player/DisplayEngine.cpp
    @@ -131,6 +131,7 @@ void DisplayEngine::init(const DisplayParams& dp, GLConfig glConfig)
                     dp.isFullscreen(), glConfig)));
         }
     #endif
    +    m_Size = dp.getWindowParams(0).m_Viewport.size();
 
         Display::get()->getRefreshRate();

**Comment by oxullo** [comment]
It works!
yeah, I missed the test.. thanks! Feel free to merge

**Comment by uzadow** [comment]
I'm confused. The second commit should only have an effect if the first commit isn't applied.
You tested app-resolution != app-window-size? And that works?

**Comment by oxullo** [comment]
Ops, my bad, I haven't pushed the revert

**Pull request merged**
