### PR TITLE
Bugfixes/missing tests

### PR DESCRIPTION
**Pull request by uzadow**

### CODE REVIEW

**Comment by scotty007** [comment]
Just out of curiosity, why Player.setCursor() has been removed?

**Comment by uzadow** [comment]
I can revert that if anyone really needs it, but the function only supports a black-and white cursor, no grayscale, no colors, and only 1-bit transparency, so it's pretty crappy. My impression is that noone ever used this function.

**Comment by scotty007** [comment]
I used it once in a while to show a cross-hair cursor when drawing interactive graphs. But I can live w/o it...

**Comment by uzadow** [comment]
Oops, ok, feel free to revert :-)

**Pull request merged**
