### PR TITLE
Mask Bitmap support for RasterNodes (#386)

### PR DESCRIPTION
**Pull request by scotty007**
TODO:
- [x] documentation
- [x] unit tests for non-ImageNode RasterNodes ?
- [ ] ~~support for canvas protocol maskhrefs~~ - maybe later
- [ ] ~~expose RasterNode::getMaskBitmap() to python~~

### CODE REVIEW

**Comment by uzadow** [comment]
Looks nice, this has been missing for a long time :-).

However, the test contains lots of redundant duplicated code. Can we get rid of that?
Also, I'm not sure how to interpret the TODO comments: Are you planning to do this? Do you think it should be done before a merge?

**Comment by scotty007** [comment]
I use duplicated test code to check the very same behavior for both ways to set a mask (same scene, same result images). The way the mask bitmap is set internally differs a bit, so I thought testing both against each other would be good.

The 1st point in the TODOs is mandatory, of course, and will be done before a merge. The other 3 are more like questions for a possible discussion here. I'd vote for a python side getMaskBitmap() (very easy to implement), while I could live w/o the other 2 points. I don't know yet how much work it'd be to add canvas protocol support (RGB-to-I8 conversion, circular canvas dependencies checks, etc.).

**Comment by uzadow** [comment]
Is there a particular reason you have this branch on your own github account? If you'd move it to the main libavg repository, I could commit as well :-).

Anyway, if we want to run a test twice in different configurations (in this case, with and without mask bitmaps), why not just do something like:
```python
for useMasks in (False, True):
    root = self.loadEmptyScene()
    [...]
```
And have some 
```
if useMasks:
    node.setMaskBitmap(avg.Bitmap("media/mask4.png"))
```
in appropriate places? That way, we don't have to fix bugs and generally maintain code twice because of duplication.

Regarding `getMaskBitmap()`: First, there is no `getBitmap()` either and noone has asked for it.
So: When would you want to use that api? If we can avoid adding it, we can avoid removing it when we switch from href= to src= handling (see https://www.libavg.de/site/projects/libavg/wiki/IdeasForExpansion).

A unit test for a non-image mask should be there, I think. It doesn't need to be big.

I'm not sure how much work adding canvas support would be, but it would be really nice to have (a lot faster, especially for big bitmaps). Circular dependencies or RGB->I8 conversion shouldn't be issues. The dependency just has to be registered with the Player class, which takes care of that. The conversion happens when the mask texture is used in the shader and should be done in 2-3 lines of code. Or we just use the alpha component of the canvas as mask - then it should work without any changes (if I remember correctly).

**Comment by scotty007** [comment]
Ah, you can merge the pull request, but you can't contribute code, right? If I push this branch to the libavg repo, will I need to create a new pull request and close this one (loosing the discussion here)?

I will change the duplicated unit test code and add tests for `ImageNode` and `WordsNode`, soon.

`getMaskBitmap()`: canceled

I'm afraid I don't have time to get into the canvas support yet. But, yes, it would be cool to get it done. Even on my quite fast machine (Core-i7, GTX-560), the frame time jumps to >20ms every time I update the mask in the `dynamicmask.py` sample. With an offscreen canvas, there's no need to transfer the bitmap from VRAM to RAM and back, right? And auto-rendering the canvas should do all the necessary work for a *real* dynamic mask.
I'd like to leave this out for now and get the rest merged ASAP, because, ahem, I need the bitmap support right now ;-)

**Comment by uzadow** [comment]
Ok, so let's keep the branch in your repo for now, do the test changes & then we can push :-).
I won't be here from this evening to monday, though. If you're sure things work and you need the changes, just push yourself.

**Comment by uzadow** [comment]
Nice!

**Pull request merged**
