### PR TITLE
Coding conventions

### PR DESCRIPTION
**Pull request by pwmvx1289**

### CODE REVIEW

**Comment by pwmvx1289** [comment]
I'm not very sure whether these are correct.

**Comment by uzadow** [comment]
The first and third commits are good, thanks.
There is no reason for the second commit (844bf2751), however

**Comment by pwmvx1289** [comment]
@uzadow Thanks I will delete the second commit.

**Comment by pwmvx1289** [comment]
@uzadow Is this PR able to be merged?

**Comment by pwmvx1289** [comment]
@uzadow Is this PR able to be merged?

**Comment by uzadow** [comment]
All except the last can be merged.

**Comment by pwmvx1289** [comment]
@uzadow Why is that so?

**Comment by uzadow** [comment]
Also, I don't think we should change code in the oscpack directory, because this code is from an external library which was imported to libavg. I'd like to retain the ability to perform a meaningfull diff between the original code and our version.

**Comment by pwmvx1289** [comment]
@uzadow Noted.

**Pull request closed without merging**
